### PR TITLE
Upgrade projects and packages to target .NET 4.5

### PR DESCRIPTION
**Pull request by BrainCrumbz**
Also: explicitly add RhinoMocks to packages; save VB specs project changes after opening it in VS 2013 Community Edition.

### CODE REVIEW

**Comment by amirrajan** [comment]
This looking good so far on my end. Going to get @mattflo to give y'all collaborator permissions early next week. I wouldn't stress too much about making it Mono compatible (I'll work through that as needed).

**Comment by BrainCrumbz** [comment]
great. Have you got a chance to also look at first example of asyncBefore implementation? It's mentioned in the issue

**Comment by amirrajan** [comment]
I'll take a look this weekend. :-)

**Comment by amirrajan** [comment]
I've gotten NSpec building on mono here: https://github.com/mattflo/NSpec/tree/mono

There were minor changes to the NSpect2012.sln and I added a `build.sh` I'll send a pull request from my `amirrajan` account to your VS2015 branch. I'm also going to get the `console_output` tests working on mono.

**Comment by BrainCrumbz** [comment]
Ok, waiting for that!
As soon as we decide how to proceed on async, maybe we could stop working on BrainCrumbz forked repo and move the ongoing work to the proper branch in NSpec original repo, if you agree.

**Comment by amirrajan** [comment]
I'm fine with that. Go ahead and merge this in (since you are a collaborator yay!). And I'll add my mono stuff in to the main line.

**Pull request merged**
