### PR TITLE
chore(solution): port to .NET Core 1.0

### PR DESCRIPTION
**Pull request by BrainCrumbz**
This PR is to keep track of current work happening. 

Here taking notes of tasks emerged until now:
- [x] Confirm current working state of NUnit on .NET platform standards: net framework 4.6, net core 1.0
- [x] Confirm current state of technologies currently used by NSpec (reflection, marshaling, ...) on Net Core 1.0
- [x] Build NSpec library on .NET Core
- [x] Build & pass NSpecSpecs test on .NET Core
  - [x] One minor case is still TBD if it should be ported or not: decide and port/comment
- [x] Build sample specs on .NET Core and run them through some custom console runner
- [x] Decide how the two versions of NSpec (for classic .NET framework and .NET Core) should coexist
  - [x] Build NSpec library on .NET 4.5.2 with .NET Core tooling
  - [x] Build & pass NSpecSpecs test on .NET 4.5.2 with .NET Core tooling
  - ~~Separate repos? [Hopefully not]~~
  - ~~Separate solutions? [Maybe not] Different tooling?~~
  - ~~Separate projects? [Maybe that's the way, with conditional flags and/or PCL shared project] Different tooling?~~
  - Same project, separate code when needed [in a few, concentrated points, with conditional flags]
- [x] Create console runner compatible with `dotnet test`
- [ ] Create console runner compatible with VS test running environment
- [ ] Port current VS test adapter 
- [x] Cut all asserts beside a single _is-true_ type of assertion
  - [x] Remove NUnit dependency from NSpec
- [ ] Setup NuGet packaging
  - [ ] Update nuspec file format, if still relevant
- [ ] Turn to minimum feasible *netstandard1.X* framework version
  - [ ] Remove package.json *imports*, if not relevant

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Are we sure about merging this into master? There still are things to clear up. First of all, how to still produce a proper NuGet package out of source code.

**Comment by amirrajan** [comment]
>First of all, how to still produce a proper NuGet package out of source code.

Not sure what you mean.

**Comment by BrainCrumbz** [comment]
I mean: did some quick tests running `dotnet pack` and `nuget pack` on this branch, and generated package does not seem to work properly. E.g., DLLs are copied but references are not added to client project.

**Comment by amirrajan** [comment]
Personally not a big deal for me since the dotnet core nuget packages haven't been deployed yet (and we have the old build tagged if there needs to be some kind of emergency release).

**Pull request merged**
